server:
  port: 8088
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///shop
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.226.130
mybatis:
  type-aliases-package: com.qf.entity
  mapper-locations: classpath:com/qf/shop/shop_kill/dao/mapper/*.xml